### ISSUE TITLE
Tax not carrying over..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#13]
From woo.angelleye.com, I loaded the web app using the QR code, and then I clicked to View Pending Orders.  I selected an order with $10.00 product and .77 taxes, for a total of $10.77.  When I click the button to send to the Here app, it only carries over $10.00 total.

**Comment by angelleye** [comment]
@kcppdevelopers As discussed in Slack, when loading pending orders we can go ahead and apply tax at the order level based on the WC tax applied to the order.

**Comment by angelleye** [comment]
@kcppdevelopers I'm a little confused here.  I remember that we discussed passing tax at the order level instead of the item level and that would be easier for you.  What I'm seeing, though, is that you're adding tax as a line item on the cart instead of using the actual tax field that the PayPal Here app provides:

![image](https://user-images.githubusercontent.com/629241/37707666-f50f3646-2cd1-11e8-820e-085ef3a0916f.png)

There is a setting in the Here app to disable tax, so we would need to account for that.  How does the Sideloader expect us to pass tax?

**Comment by kcppdevelopers** [comment]
@angelleye order level tax parameter not available. 

CreateInvoice API request and PayPal Here request  parameter both are same. In Woo product level tax calculation little bit different and it's almost not match with total tax calculation. so I have passed tax calculation as line item.

Could you please give me your comments or suggestions on this?

**Comment by angelleye** [comment]
We can review this more later and try to figure out the best overall solution.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-40
