### ISSUE TITLE
WC order did not update after marking paid from mobile.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#14]
As a test, I loaded Pending Orders from the mobile web app, which displayed 4 pending orders in my WC system.  

I selected one of them, marked it paid with cash, but the WC order status is still pending, and it still shows up in the pending list instead of being marked as completed / paid.

**Comment by kcppdevelopers** [comment]
@angelleye I have tested on woo angelleye com with order no 13153 and for me it's working fine. could you please re test again for me?

**Comment by angelleye** [comment]
@kcppdevelopers I have still never been able to get an order to update after marking it paid in the Here app.  I click to return to the web app dashboard, but the WC order status never updates.

**Comment by kcppdevelopers** [comment]
@angelleye now WC order status updates work for both Android and iOS.
