### ISSUE TITLE
WC Checkout Page Gateways

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#16]
Right now PayPal Here is showing up in the list of payment methods during a regular checkout on the website.  Is that intended to be used by the buyer at this point?  If the buyer selects PayPal Here are we saving the order in WC so that it can later be paid within the Here app?

**Comment by kcppdevelopers** [comment]
@angelleye yes, it will work like other gateways when user click on place order button it will open in PayPal Here app.

**Comment by angelleye** [comment]
@kcppdevelopers I'm still not following.  The seller is the one that would typically use the PayPal Here app for processing orders.  If a standard buyer is using the regular website to pay for an order like any other normal Woo order, how would they checkout when select PayPal Here on the checkout page?

**Comment by kcppdevelopers** [comment]
@angelleye I am agree with you, Let me hide PayPal here gateway on checkout page.
