### ISSUE TITLE
Web App - Remove item from cart..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#19]
Right now I don't see any way to remove an item from the cart/order when using the web app..??

**Comment by angelleye** [comment]
@kcppdevelopers When we do this in the web app, it looks like a page reload, but we see in your commit that you have AJAX calls in place.  Can you clarify this is done with AJAX?

**Comment by kcppdevelopers** [comment]
@angelleye yes item removal functionality work base on AJAX but on response we are loading page for refresh page exclude that in html.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-39
