### ISSUE TITLE
Web App - Home Button

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#20]
When browsing the web app there is no way for me to get back to the dashboard easily.  We have our little menu button (3 horizontal lines) but it's not doing anything right now.  Let's add an item in there for the Dashboard.

**Comment by angelleye** [comment]
When we use this button to move back to the dashboard we should clear out existing order details so that we're starting clean.

**Comment by kcppdevelopers** [comment]
![menu](https://user-images.githubusercontent.com/13145461/37957451-902cc7da-31cb-11e8-92ee-9fdebe98fbda.png)
