### ISSUE TITLE
WC REST API 

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#26]
I just did a fresh install of WP on a new dev laptop.  I installed our dev branch here, and I was immediately given a notice in the admin panel that the WC rest keys were not available.  I generated that through the plugin settings, and the admin notice went away.

However, on the front end of the site I still getting a notice about the WC API keys not being available.  I disabled the Here plugin and the front-end message was gone.  I then re-acticated the Here plugin and the message did NOT come back, but something about that initial clean install did not go smoothly with the keys.

**Comment by angelleye** [comment]
@kcppdevelopers What feedback are you waiting for on this one..??  Did you specifically test a brand new, clean install of WP and the plugin after making this adjustment to ensure the notices are working properly?

**Comment by kcppdevelopers** [comment]
@angelleye  I have resolved this issue already and tested on fresh setup it's working..
