### ISSUE TITLE
QR Code in Order Screen

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#28]
On the order screen in WC the QR code for PayPal Here is showing up even on orders that are already in Processing status.  The QR code for Here should only show up for orders that still need to be paid.

**Comment by kcppdevelopers** [comment]
This issue I have already resolved in previous milestone.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-38
