### ISSUE TITLE
Testing Phase 1 Feedback: Design Issues Suggestions

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-here-woocommerce#31]
![image](https://user-images.githubusercontent.com/11312949/38295341-214696c4-3807-11e8-82bd-f4d9529ce5d6.png)

The close button is not center aligned also need to be 2 pixel big

+  And - background should match the border color of the input field

The add item button in my last screenshot is blue while in the product selection popup its while . 2 suggestions.
- make it blue.
- it would be great to add that to footer on that popup

**Comment by angelleye** [comment]
Yes, I would like to get a better design overall for these types of windows in the app.  We'll get some wireframes put together.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-36
