### ISSUE TITLE
Improvement to item removal.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#34]
In #19 we added the ability to remove items from the cart.  It looks like this is happening as a page reload and would be better with AJAX instead.

**Comment by angelleye** [comment]
Original issue actually does show AJAX, so I'm a bit confused.  Left a note there as well.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-34
