### ISSUE TITLE
Cart User Experience - Shipping confusion

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#35]
When I add a new item to the cart it shows Shipping Free!   Shipping options prior to gathering billing/shipping info should be based on the WooCommerce option for whether to include shipping on the cart page.

![image](https://user-images.githubusercontent.com/629241/38350342-7bba8a7a-3870-11e8-9f35-7c4962770061.png)

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-33
