### ISSUE TITLE
Proxy server required for web app..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#37]
For some reason when @iMansoorAliKhan pulls the web app up on his phone he has to connect through a proxy in order to get it to work.  This is not required when he views the regular woo.angelleye.com site, though, so we're not sure what's going on with that..??

**Comment by angelleye** [comment]
This is what he gets for source if he does not connect to a proxy before loading the app...

![image](https://user-images.githubusercontent.com/629241/38351205-1a9851d8-3874-11e8-8dba-aff83e5be0dc.png)

Then when he connects to a proxy server it works fine.  Again, this is not required when he browses http://woo.angelleye.com/.  Only when he browses /paypal-here

**Comment by kcppdevelopers** [comment]
@angelleye It seem firewall block that URL for specific IP

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers  did you made any adjustments? because for me now its working fine.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan No, It seems firewall blocking issue.

**Comment by iMansoorAliKhan** [comment]
Now its working fine ,

**Comment by iMansoorAliKhan** [comment]
Did you made any adjustments for this? I dont see any commit?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan No, I do nothing for this issue.
