### ISSUE TITLE
Pending Order List

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#40]
I'd like to make an adjustment to the display name on the pending orders list.  Right now I have the following pending orders in WC...

![image](https://user-images.githubusercontent.com/629241/38365418-d82101a0-38a1-11e8-8d8f-bd4669aace4b.png)

When those orders are pulled up in our pending order list, though, it shows N/A instead of the name for one of the orders.

![image](https://user-images.githubusercontent.com/629241/38365443-f1e7b5e8-38a1-11e8-9dc6-71e9d1f9e0e1.png)

That order does not have any billing/shipping info, while the others do, so we must be pulling the billing name here instead of the user/customer name.  Would like to adjust so we always see a name just like the actual WC list shows.

**Comment by angelleye** [comment]
Seems like WooCommerce is using the Billing Name when available, but when it's not then it falls to the name in the user account.  We should do the same.

**Comment by angelleye** [comment]
Now when I look at the Pending Orders list I see some with nothing but the order # in the name column..??

**Comment by angelleye** [comment]
Also, the eye ball on the right side of the row is kinda creepy when there are is a big list of pending orders.  Why did we add that?  What's its purpose?

**Comment by angelleye** [comment]
Ah, I see now that I cannot view the order without clicking the eye.  I actually preferred it the other way, where we could click the row to view the order without the need for a specific eyeball icon/button.  

But then the trash can also needs to work.  Right now it's just "selecting" the row when I try to push the trash can, which is the same thing that happens when I push anywhere now other than the eyeball.

**Comment by angelleye** [comment]
On desktop Chrome browser the trash can is working, but on mobile Chrome Browser (Android) it is not.  It just highlights the row gray.

On desktop the rows highlight gray as I hover over them, but it never stays gray like it does on mobile browser.

**Comment by kcppdevelopers** [comment]
@angelleye I have remove "eye ball" icon on issue #32

**Comment by kcppdevelopers** [comment]
@angelleye Now we are doing same thing on name column as woo.

**Comment by angelleye** [comment]
@kcppdevelopers The trash can is still not working for me on Android Chrome.

**Comment by angelleye** [comment]
@kcppdevelopers The trash can is still not working for me on Android Chrome.
