### ISSUE TITLE
Clear sale updates WC order status to failed..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#41]
I opened a pending order and sent it to PayPal Here.  I then used "Clear Sale" in the Here app to cancel the order, which automatically redirected me back to our web app dashboard.  The order I was in got updated to Failed in WC.

I'm not sure if I like that or not.  We'll discuss this more and try to get some user feedback for 1.0 release.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-32
