### ISSUE TITLE
WC Order Payment Status not updating properly..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#43]
Just a little bit earlier today I ran a test and the WC order was marked Processing and had PayPal Here as the payment type...

![image](https://user-images.githubusercontent.com/629241/38369050-7558e5f0-38ac-11e8-9f6b-a56dfb681ef1.png)

I just now ran another test, though, and the order did update to Processing, but the other detail for payment did not come through...

![image](https://user-images.githubusercontent.com/629241/38369110-989437b8-38ac-11e8-9dbb-4b1a1bb961e9.png)

Not sure what went wrong this time..??

**Comment by angelleye** [comment]
The only difference is that the order I did previously was done through the pending orders list in the web app.  This recent test was done by scanning the QR code from an order directly.  I don't think that should have any affect on the post-payment processing, but that's the only thing I can think that was different.

**Comment by angelleye** [comment]
Just ran another test and the same problem happened.  I don't know what changed between a few hours ago and now, but something broke our payment details in the WC order status update.

**Comment by angelleye** [comment]
I just did another test here now, and it looks like the details did come in this time...

![image](https://user-images.githubusercontent.com/629241/38407056-a05cf840-393d-11e8-8099-e32230b6c825.png)

However, it says Paid @ 6:52 am and it's 1:52 am here right now, so not sure where that time zone is coming from..??

**Comment by kcppdevelopers** [comment]
@angelleye As per discussion we have resolved issue using WordPress timezone setting.
