### ISSUE TITLE
Add item is getting hung up..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#46]
This was working previously, but now when I try to add a new item to a new order or an existing order from the web app it's getting hung up.

I'm able to view the product list and select a product.  It pops up the secondary window where I can choose the QTY and attributes, but then when I click the Add Item button from here it never moves on.  I get stuck a default windows/browser spinner and it won't actually add the item and move on.

![image](https://user-images.githubusercontent.com/629241/38386779-6fcc1948-38db-11e8-891e-307f94bcb748.png)

**Comment by iMansoorAliKhan** [comment]
Still seeing this when coming back from PayPal here app;
![image](https://user-images.githubusercontent.com/11312949/38405948-0700c6aa-398c-11e8-93bd-8e288a50f595.png)

Along with many other 404 resources not found

**Comment by iMansoorAliKhan** [comment]
![image](https://user-images.githubusercontent.com/11312949/38405967-26438872-398c-11e8-8611-bcc1f8b59e83.png)

**Comment by iMansoorAliKhan** [comment]
But I dont see that > reference result is not defined

**Comment by angelleye** [comment]
@kcppdevelopers As mentioned above, the Add Item button is functioning now, but we're still seeing errors in console that need to be cleaned up.
