### ISSUE TITLE
PayPal REST APIs to update WC order status..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#47]
Right now the only way the WC order status gets updated is if the user remembers to click "New Sale" after completing a payment in the PayPal Here app.  This is going to get missed a lot, and WC orders will not get updated properly.

We should be able to add a fail-safe to this by using the PayPal REST APIs.  Our plugin could setup a CRON job that runs on a given interval, and this script could check all of the WC pending orders against the PayPal API to see if it's been paid or not.  Any pending order that comes back as paid by PayPal would be updated accordingly.

**Comment by angelleye** [comment]
There isn't a specific Webhook for "PayPal Here" transactions, but we should test webhooks in general to see we get anything at all out of the current webhooks for Here transactions.  If so, we may be able to use that to update the WC order status.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-29
