### ISSUE TITLE
Problems again with updating the order after a completed sale..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#50]
I just did another test on the current dev branch.  Upon completing the order in PayPal Here and clicking New Sale, I was returned back to the web app, but it sent me to the normal dashboard screen.  I did not see the success message in our app like I was seeing before.

The order status in WooCommerce DID update to Processing, and it does show Paid, however, it does not show the transaction ID or the PayPal Here payment type the way it did before.  We had this issue before and it was since fixed, but now it just happened to me again.

![image](https://user-images.githubusercontent.com/629241/39157197-5cbe0562-471f-11e8-8912-6c369ffb6aa5.png)

**Comment by angelleye** [comment]
@kcppdevelopers I don't know what's going on here, but this is now happening again.  This is about the 4th time this has gone back and forth.  It happens, I show you, you fix it, then it works fine for me, but then next time you commit changes in some other issue this gets broken again.  Are you somehow merging old code..??

Once again, I created a new order and processed it with the Here app.  The WC order status did update, but it did not include the PayPal Here payment method and PayPal Here Invoice.  It just looks like this again:

![image](https://user-images.githubusercontent.com/629241/39537455-3d7535a4-4dff-11e8-869a-28765c42e480.png)

**Comment by kcppdevelopers** [comment]
@angelleye I found issue when order created from admin side payment method not selected from selectbox.
We have added payment method name when order created from web app but forget to handle case when order created from admin side. now I have handle that case and will work for both cases.

**Comment by angelleye** [comment]
@kcppdevelopers One thing I'm still noticing here that is different when creating the order from the web app vs. creating the order in the WC admin panel.

If I create the order from the web app, then when I process with PayPal Here and click New Sale, I'm returned back to our web app and I do see the green message that says it was successfully processed.  However, if I create the order from the admin panel and then load that order in the web app and process it with Here, when I'm returned back to the web app I do NOT see the green successful notification at this point.

In both cases the WC order details are updating properly now, but we need the entire experience to the be the same no matter how you create the order.

Since the PayPal Here app itself has a "Success" message, I think it's actually better if we do not have our own additional success message.  So I'd like to remove this green message which is showing up when the new order is created from within the app.

![image](https://user-images.githubusercontent.com/629241/39606793-e6dd795a-4efc-11e8-8487-8c47bb13b8e3.png)
