### ISSUE TITLE
InvoiceId vs. transaction_id

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#51]
In most cases PayPal returns a transaction_id which we are storing in order post meta data as `transaction_id`.  With PayPal Here they return an `InvoiceId` which we're saving accordingly.  Both of these are ending up with the same value, though, which seems redundant.  Do we need both in the case of PayPal Here?

![image](https://user-images.githubusercontent.com/629241/39327774-ab01bdea-495e-11e8-8f0b-50cdeade9d72.png)

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-28
