### ISSUE TITLE
Tax getting added when it shouldn't..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#53]
Right now we're creating new orders from the web app and it's adding tax to the order whether I have any address or not.  I double checked our tax settings in WC and we only have tax applied to the state of MO.

I first created the order and added the item, and it didn't have any address at this point, but it still applied tax.  We then added a CA address to see if it would adjust the tax at that point, but it did not.  

I then tried to push on the tax so I could clear it out myself, but nothing happens when I push on the tax line (like it does for shipping/discount).

I have no way to get rid of the tax on the order.

**Comment by angelleye** [comment]
To test, we completely removed all tax rules from WooCommerce, and now the new orders from the web app are no longer applying tax.  Again, though, with a MO rule setup, it was apply tax even before an address was added, as well as after a non-MO address was added.

**Comment by kcppdevelopers** [comment]
@angelleye 

![tax_module](https://user-images.githubusercontent.com/13145461/39362320-ae2c9c2a-4a43-11e8-881f-45fa3ce26d18.png)

when user push on the tax we should display like this right?

**Comment by angelleye** [comment]
@kcppdevelopers yes, and those rules would be pulled from WooCommerce.  We would also need the ability to remove tax altogether if necessary.

**Comment by kcppdevelopers** [comment]
@angelleye In WooCoomerce Tax base calculation is base on user address, when order update tax automatically calculated base on user address. if we forcefully remove tax but when order update by default automatically added again.

**Comment by iMansoorAliKhan** [comment]
I tried to add a new order but no tax applied automatically even i fill in correct Missouri address.  Do I have to select the tax on my own and system will be applying that automatically?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Could you please confirm tax is enable on admin side?

**Comment by angelleye** [comment]
@kcppdevelopers I'm actually having other weird issues with tax now in WooCommerce in general.  

First, I see that somebody keeps creating a tax rule on woo.angelleye.com that applies tax to every order.  Not sure if that's @kcppdevelopers or @iMansoorAliKhan..??

I am removing that because I want to be able to test tax showing up only for the MO rule I have setup.  For some reason, though, even in WooCommerce directly, when I create a new order that does NOT include any address it's still applying tax to the order.

This is only  happening when I'm logged in and creating an order from the admin panel.  If I'm not logged in and I just go through an order as if I'm a regular buyer then it is not apply tax during checkout.  Again, though, it's always applying tax regardless of any tax rules in WC when I create the order from the admin panel.

So it's not a Here specific problem a this point, but I'm going to need some help figuring out what's going on here.

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers  yeah I'm checking on woo.angelleye and all the tax rules were defined by Andrew. all I did was , for testing purpose, changed the tax on from shipping to billing to see if that gets applied or not.

For me first time default tax was applied but next time further it was not applied but it didnot applied tax at all even if I entered Missouri address as well.

**Comment by kcppdevelopers** [comment]
@angelleye I have not applied any changes on tax rules in woo.angelleye.com. yes right when user create order from admin side that time order assign to that particular user and use address data of user and calculated tax base on address data.

Again Woo Tax calculation base on user address data so if user already login and created data from web app/ from admin side tax will be calculated by default.

**Comment by angelleye** [comment]
@kcppdevelopers That's why I'm confused, though.  I'm creating a new order in the admin for a guest buyer and I don't fill in any address at all, but it's applying tax even though my only rule is configured for the state of MO.

Again, this is a general woo thing, so I won't let it stop our progress on PayPal Here, but I'm just not sure why it's happening.

**Comment by angelleye** [comment]
@kcppdevelopers Take a look at this video.  Do you have any idea why tax is getting calculated on the WC order in this case?

http://fiber.angelleye.com/temp/woocommerce-tax.mp4

**Comment by angelleye** [comment]
I think this has something to do with the individual product classes that are set or something.  This doesn't happen with other items I've tested with.
