### ISSUE TITLE
Add verification to deleting invoices and items.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#54]
In #32 we added the option to delete an invoice from the list.  This is working, however, it does not give me any sort of an "Are you sure you want to delete invoice #1234" type of dialog.  It just deletes, so if I accidentally push it, I can't cancel it.  We need to add this verification notice.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-26
