### ISSUE TITLE
More strange new order issues.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#55]
While trying to test new orders from the web app we're getting lots of weird issues.

- Adding $11 flat rate shipping (which is setup in WC) even though we don't have any shipping address added.

- It's somehow holding previous order data when I try to create a new order.  For example, I created a new order and added a single item, however, the order wound up with multiple items on it, and it also had a name already included when I viewed the new order on the pending list inside the web app.  I had not yet added any name, though, so it's picking this from a previous order for some reason.

Video Demo:  http://fiber.angelleye.com/temp/paypal-here-woo-weird-orders.mp4

**Comment by iMansoorAliKhan** [comment]
Okay the flat shipping now is not applied by default but when I enter shipping address for Missouri shipping address but that tax didn't get applied.

Also, when I have already added a data in a pending order then clicking on continue adding billing /shipping information actually remove that data and I have to re-enter all that again... Kinda frustrating...

Another thing I have noticed that When filling shipping / Billing , the email provided is not stored in order data ( not sure how we are processing the data )

**Comment by angelleye** [comment]
@iMansoorAliKhan Are you talking about creating new orders from within the web app of the plugin?  I'm a little confused about the work flow you are referring to here..??

**Comment by iMansoorAliKhan** [comment]
Yeah, I'm talking about the web app, I am little confused here too as how the shipping will be applied,
In woo settings you have set to hide shipping until address is entered, but when I do enter shipping address even billing address, nothing happens at all. Not sure how that is going to work???

**Comment by angelleye** [comment]
I'm going to go ahead and close this issue for now because it's very broad, and I did go ahead and release the 0.1.0 beta today.  We can create a new issue in the next milestone if we find that we're running into more problems here.
