### ISSUE TITLE
Choose from existing WooCommerce customers when creating new orders in app.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#57]
* [Product page comment](https://www.angelleye.com/product/paypal-here-woocommerce-pos/).

When creating new orders from the web app we need a way to choose from existing customers in the WooCommerce system and fill out the billing/shipping based on the chosen customer.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-25
