### ISSUE TITLE
Web App - Add Item

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#6]
When adding an item to an order we'll follow the design model that the PayPal Here app itself uses.

![image](https://user-images.githubusercontent.com/629241/32660108-241e6454-c5e7-11e7-8a67-0bed2a81117d.png)

Attributes / Variations form WooCommerce should display accordingly in this view.  For example, in the screenshot we have "Sizes" with options for Small and Large, where Large adds a $2.00 upcharge.  All attributes/variations should be available here as sections.

Tax rules should also be included here so people can choose whether or not to apply a particular tax rule to this item being added.  

All attribute/variation/tax data will be pulled from WC using the REST API.

**Comment by kcppdevelopers** [comment]
@angelleye  I am little bit confused about tax rule drop down, I think it's not required on product level.

Please Let me know your suggestion.

**Comment by angelleye** [comment]
@kcppdevelopers The screenshot is based on what PayPal Here has within it.  So yes, at the product level you can specify whether or not taxes need to be applied to that particular product.  For example, you might have an order where multiple items are included, but not all items are taxable, so you would specify a tax rule for the items that do require it, and leave it off for items that don't.

**Comment by angelleye** [comment]
@kcppdevelopers In WooCommerce when creating/editing a product, under General Settings is an option for Tax Status:

![image](https://user-images.githubusercontent.com/629241/34562565-9c01ecc2-f114-11e7-86f7-fab68229e77e.png)

So it would be good to build the product screen based on that.  If taxable, then the tax rule would be available on the PayPal Here web app screen with the tax rule that would apply automatically selected (but could be adjusted if necessary).  If the WC item is not taxable, then the tax drop down on the web-app screen would be disabled with a message that the item is not taxable per WC settings.
