### ISSUE TITLE
Compatibility with WooCommerce Point of Sale..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#61]
* https://wordpress.org/support/topic/integration-with-woocommerce-pos/
* https://mail.google.com/mail/u/0/#inbox/1635a0d8fec5c480

>I am using the plugin slightly differently than designed as i'm using woocommerce pos to create the order and push the order through to the paypal here app. (just choosing your paypal here as the pament method) .This means that I don't need to open your web interface to push the order to paypal here.
>
>Here's a quick and dirty screen capture of how i'm using your plugin using woocommerce point of sale (https://codecanyon.net/item/woocommerce-point-of-sale-pos/) - as you can see the process is pretty slick - stuff that isn't working is the stock reduction as shown and a couple of other things such as receipt printing in pos but I can get over that in the short term.
>
>http://fiber.angelleye.com/temp/woo-paypal-here-61.MP4 #60 

I asked for another video showing how he has things configured...

>The beauty of how this works is that i've not set it up any differently to your documentation - the only exception is that i've changed the paypal here endpoint in your plugins settings to my pos url (point-of-sale/the-craft-studio/main) - I then select your plugin within the available payment gateways that appear in woocommerce and make it available to use in pos. POS then sees this as an external gateway and just fires the url built by your plugin - it just happens that the payment url in paypal here when on a tablet with the here app installed works. I think part of the problem is that on return, currently it just reopens a new instance of pos rather than returning and closing the window (completing the sale) that was initiated. This is what stops POS from realising the sale is complete and doing all the other things it would normally do (eg printing receipts etc).  That's just my assessment of what could be going on but i'm no developer!
>
>I'll work on getting you a video over when I have some time today.
>

> Not sure how useful this will be but here's a vid of my config on my dev site.  One thing I forgot to mention is that the pos plugin has a concept of outlets and registers and you can have multiples of each - this would have an impact on the url end point - for me I only have one outlet and one register so pretty straightforward but for those with multiple outlets and/or registers it would be difficult.
> 
> 
> Also - the second video shows the issue with the attributes in the paypal here cart. It appears that it's the attribute meta showing for all items in the cart, not the title like I first thought.
> 
> Let me know if you need more info or explanation of any settings in the vid.
>http://fiber.angelleye.com/temp/video-1526327424.mp4
>http://fiber.angelleye.com/temp/video-1526328440.mp4

**Comment by angelleye** [comment]
It seems what he's doing here is an unintended use of our plugin, but it does look like it would work rather nicely except for the inventory not updating properly.  We should look into exactly what is going on here, and get our plugin working well with WC POS, and we could piggy back off that to get more users quickly.

**Comment by iMansoorAliKhan** [comment]
Another user asking the same  https://wordpress.org/support/topic/integration-with-woocommerce-pos/

**Comment by angelleye** [comment]
I've provided quite a bit more info in the original notes for this issue.

**Comment by iMansoorAliKhan** [comment]
Moved to jira : https://angelleye.atlassian.net/browse/PHFW-8
