### ISSUE TITLE
[woocommerce_rest_cannot_view]

### ISSUE THREAD

**Issue by gradywoodruff** [angelleye/paypal-here-woocommerce#62]
I am using woo-paypal-here on a site with https and paypal-here works on the non-secure local test site but gives me the error `Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]`

**Comment by iMansoorAliKhan** [comment]
@gradywoodruff can you tell me where you are seeing this error? in log or somewhere on your site?
Also, whats your WC version  ?

**Comment by gradywoodruff** [comment]
@iMansoorAliKhan I'm using Woocommerce 3.4.1. It is happening on both the new orders and pending pages.

https://highoncap.com/paypal-here

I think it is something about the https because it works on my localhost, but I'm unsure of were i would need to add validation or permissions for this

**Comment by iMansoorAliKhan** [comment]
can you please make sure you have configured PayPal here and also generated woocommerce REST token in **Woocommerce > settings > Payments > paypal here ??**
Can you share screenshot of settings?

**Comment by gradywoodruff** [comment]
Yes, thank you
<img width="1226" alt="screenshot 2018-06-05 12 19 07" src="https://user-images.githubusercontent.com/748199/40989251-34d2f73e-68bb-11e8-941c-bb2e03b04484.png">
<img width="904" alt="screenshot 2018-06-05 12 20 21" src="https://user-images.githubusercontent.com/748199/40989252-34e38c84-68bb-11e8-8f98-74e6265b2708.png">

**Comment by angelleye** [comment]
@iMansoorAliKhan Please make sure this has been moved into Jira, and again, if the project still needs to be setup there you can have Gary do that.

@gradywoodruff We're getting our stuff moved into a new system so we've been a little delayed.  Sorry about that.  We'll get this setup and start working on it in our next 2 week sprint of work.  We'll be sure to keep you posted.  Thanks for the feedback!

**Comment by iMansoorAliKhan** [comment]
@gradywoodruff  We have this adjusted in our last update, it would be good if you can update to latest release and give it another shot.
We will appreciate your feedback.

Closing this now but feel free to respond here again if you still continue to see the issue.
Thanks!

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PHFW-20
