### ISSUE TITLE
Adding shipping by default???

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-here-woocommerce#63]
![image](https://user-images.githubusercontent.com/11312949/40936114-ad4a41e4-6853-11e8-890c-de5f46e93c88.png)

Shipping options:

![image](https://user-images.githubusercontent.com/11312949/40936125-bcb5e246-6853-11e8-98d0-58d9c0b292cd.png)

**Comment by angelleye** [comment]
@iMansoorAliKhan We need to start adding stuff like this to Jira instead of GitHub.  Please create the issue there, and if there isn't a project setup for it yet you can have Gary create it.

**Comment by iMansoorAliKhan** [comment]
@angelleye  Sure, I will move this to Jira now. 
moved to : PH-1 On Jira
