### ISSUE TITLE
Web App - Apply Discount

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#8]
From the Order Screen (#7) the user can apply a discount, and this view would be displayed for that:

![image](https://user-images.githubusercontent.com/629241/32660149-4d7df8be-c5e7-11e7-83fa-b7bb669ef925.png)

So the user will have the ability to enter a flat rate or percentage page discount directly, or they could also enter a coupon code.  The coupon code field should be a drop-down that also acts as a regular text field, and if you are typing in a coupon code it should use AJAX to search on the fly and update the drop down accordingly.

**Comment by kcppdevelopers** [comment]
> The coupon code field should be a drop-down that also acts as a regular text field, and if you are typing in a coupon code it should use AJAX to search on the fly and update the drop down accordingly.

@angelleye Can you please explain with more details? I think coupon code should be private right?

**Comment by angelleye** [comment]
@kcppdevelopers The person using this app would be the site owner, so they just need a quick and easy way to view all of their existing coupon codes to select one or enter it manually.

**Comment by angelleye** [comment]
@kcppdevelopers I'm clicking on the Discount line item, which does load the Discount window.  I choose to add a 10% discount and apply it, but it's not reflecting on the order details in the web app.

**Comment by angelleye** [comment]
@kcppdevelopers There should be a way to provide an attribute or something that lets the device know to use the number pad instead of the regular keyboard.  We need to set that here and for shipping.

**Comment by angelleye** [comment]
@kcppdevelopers The coupon code did get applied, so that part seems to be working now, but I'd like to fix the number pad thing as mentioned previously.

**Comment by angelleye** [comment]
@kcppdevelopers Looks like we're passing the discount to PayPal Here as a line item the same as we are tax.  Do we have the same problem there as with tax, or why didn't we use the actual PayPal Here discount field for this?

**Comment by kcppdevelopers** [comment]
@angelleye yes we have same problem as tax, shipping and discount on Android device.
