### ISSUE TITLE
Web App - Apply Shipping

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-here-woocommerce#9]
From the order screen, if the user pushes the Shipping item it would load this display:

![image](https://user-images.githubusercontent.com/629241/32660294-e2404e52-c5e7-11e7-8c10-b40bda3a830a.png)

The user can enter a flat rate or percentage based shipping amount directly, or they could also enter a postal code to have shipping rules from WC triggered and calculated accordingly for the order.

**Comment by kcppdevelopers** [comment]
@angelleye I need your suggestion for shipping popup, shipping popup textbox label text like 'Postal code' so how can user enter flat rate or percentage based shipping amount directly? should we need to changed shipping popup and add other extra option for flat rate or percentage based shipping amount?

**Comment by kcppdevelopers** [comment]
For shipping calculation WC required country and state as well for shipping calculation.

**Comment by angelleye** [comment]
@kcppdevelopers, In the tests I've run that include shipping, the shipping amount is not getting passed into the Here app.  Only the subtotal without shipping is getting passed over.

**Comment by angelleye** [comment]
@kcppdevelopers I'm still not able to get shipping to pass correctly.  You keep saying it works for you, but it has never worked for me.  

As discussed in Slack you are about to test with Chrome instead of Safari mobile.  Maybe we'll find that's where the problem lies...??

**Comment by angelleye** [comment]
@kcppdevelopers  The shipping seems to be passing correctly in iOS, but not Android.  We have asked Dheeraj from PayPal to help us troubleshoot this.

**Comment by angelleye** [comment]
@kcppdevelopers Also, I'd like to set the entry attributes on this to use the keypad on the device instead of the regular keyboard.

**Comment by angelleye** [comment]
@kcppdevelopers PayPal dev is confused about our shipping passing issue.  We say it works on iOS but not Android, right?  Can you show a screenshot of the shipping filled in on iOS so we can exactly which field it gets populated into?

**Comment by kcppdevelopers** [comment]
@angelleye yes right, Shipping amount is working fine in iOS.


1) Web APP:

![01](https://user-images.githubusercontent.com/13145461/38417165-ea0a5d94-39b4-11e8-986c-0e0bad53af65.PNG)




2) PayPal Here APP:


![02](https://user-images.githubusercontent.com/13145461/38417169-ef30996e-39b4-11e8-875d-c4c70227feca.PNG)

**Comment by angelleye** [comment]
@kcppdevelopers PayPal has confirmed there is a field mapping issue with shipping on Android.  Let's go ahead and adjust to send shipping as a line item in the cart instead of the actual shipping field for now.
